name: Update

on:
  workflow_dispatch: {} 
      
jobs:
  build:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SETLISTFM_TOKEN: ${{ secrets.SETLISTFM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Get latest setlist
        run: node scripts/pull-setlists.js
      - name: Generate production
        run: node scripts/generate-prod.js
